# Schema for the configuration files of the YouTube module.

field_wistia.settings:
  type: config_object
  label: 'Field Wistia settings'
  mapping:
    field_wistia_embed_type:
      type: string
      label: 'Embed type'

field.formatter.settings.field_wistia_video:
  type: mapping
  label: 'Field Wistia video formatter settings'
  mapping:
    field_wistia_size:
      type: string
      label: 'Wistia video size'
    field_wistia_width:
      type: string
      label: 'Wistia width'
    field_wistia_height:
      type: string
      label: 'Wistia height'
    field_wistia_embed_type:
      type: string
      label: 'Embed Type'

